### ISSUE TITLE
TaskRegisterMutation should return a TaskEdge

### ISSUE THREAD

**Issue by jgcmarins** [rafaelangical/full-relay-graphql#2]
here:
https://github.com/rafaelangical/full-relay-graphql/blob/ad7af9b1210202a9400805e16a14021491b34873/packages/server/src/modules/task/mutation/TaskRegisterMutation.ts#L39-L42

- [x] it should return a TaskEdge to update Relay connection on client side

**Comment by rafaelangical** [comment]
resolved on this commits 

server
https://github.com/rafaelangical/full-relay-graphql/commit/5f6b1f0e9ddeffd67347849df751121f32288e55

app
https://github.com/rafaelangical/full-relay-graphql/commit/0dde9e66158bd40a0f1903c7994200861b72ede1

**Comment by rafaelangical** [comment]
`{
  "data": {
    "TaskRegister": {
      "task": {
        "node": {
          "name": "sjssssssjsss",
          "description": "sjksssks",
          "_id": "5e147e926173ce3775164fdf",
          "id": "VGFzazo1ZTE0N2U5MjYxNzNjZTM3NzUxNjRmZGY="
        }
      },
      "error": null
    }
  }
}`
